// Generates src/styles/tokens.generated.css from the Figma token exports in tokens/<mode>/.
// Re-run with `npm run build:tokens` whenever the Figma exports change.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dirname = path.dirname(fileURLToPath(import.meta.url));
const tokensRoot = path.join(dirname, '..', 'tokens');
const outFile = path.join(dirname, '..', 'src', 'styles', 'tokens.generated.css');

// Figma semantic variable name -> shadcn/Base UI-style CSS variable name(s).
// Flat entries (single color) map to one CSS var; nested { background, foreground }
// entries map to a DEFAULT/foreground pair.
const SEMANTIC_NAME_MAP = {
  Border: 'border',
  Link: 'link',
  Input: 'input',
  'Focus ring': 'ring',
  'separator lines': 'separator',
  Primary: 'primary',
  Secondary: 'secondary',
  Accent: 'accent',
  Base: { background: 'background', foreground: 'foreground' },
  card: 'card',
  popover: 'popover',
  muted: 'muted',
  destructive: 'destructive',
  warning: 'warning',
  success: 'success',
  info: 'info',
};

function primitiveVarName(targetVariableName) {
  // e.g. "neutral/200" -> "--color-neutral-200", "neutral/white" -> "--color-neutral-white"
  return `--color-${targetVariableName.replace('/', '-')}`;
}

function buildPrimitives(primitives) {
  const lines = [];
  for (const [family, shades] of Object.entries(primitives)) {
    if (family.startsWith('$')) continue;
    for (const [shade, token] of Object.entries(shades)) {
      lines.push(`  --color-${family}-${shade}: ${token.$value.hex};`);
    }
  }
  return lines;
}

function resolveValue(token) {
  const alias = token.$extensions?.['com.figma.aliasData'];
  if (alias?.targetVariableName) {
    return `var(${primitiveVarName(alias.targetVariableName)})`;
  }
  // No alias recorded (shouldn't happen for this file) - fall back to the literal hex.
  return token.$value.hex;
}

function buildSemantic(tokens) {
  const lines = [];
  const unmapped = [];

  for (const [figmaName, entry] of Object.entries(tokens)) {
    if (figmaName.startsWith('$')) continue;
    const mapping = SEMANTIC_NAME_MAP[figmaName];

    if (!mapping) {
      unmapped.push(figmaName);
      continue;
    }

    if (entry.$type === 'color') {
      // Flat token, e.g. Border, Link, Input, "Focus ring", "separator lines"
      lines.push(`  --${mapping}: ${resolveValue(entry)};`);
    } else {
      // Nested { background, foreground } group, e.g. Primary, Secondary, card, muted...
      const cssName = typeof mapping === 'string' ? mapping : null;
      const bgVar = typeof mapping === 'object' ? mapping.background : cssName;
      const fgVar = typeof mapping === 'object' ? mapping.foreground : `${cssName}-foreground`;
      if (entry.background) lines.push(`  --${bgVar}: ${resolveValue(entry.background)};`);
      if (entry.foreground) lines.push(`  --${fgVar}: ${resolveValue(entry.foreground)};`);
    }
  }

  if (unmapped.length) {
    console.warn(`[build-tokens] No CSS var mapping for: ${unmapped.join(', ')} - add them to SEMANTIC_NAME_MAP.`);
  }

  return lines;
}

function buildMode(mode) {
  const modeDir = path.join(tokensRoot, mode);
  const primitives = JSON.parse(readFileSync(path.join(modeDir, 'primitives.json'), 'utf8'));
  const tokens = JSON.parse(readFileSync(path.join(modeDir, 'tokens.json'), 'utf8'));

  const primitiveLines = buildPrimitives(primitives);
  const semanticLines = buildSemantic(tokens);
  return { primitiveLines, semanticLines };
}

const modes = readdirSync(tokensRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name);

if (!modes.includes('light')) {
  throw new Error('Expected tokens/light/{primitives,tokens}.json to exist');
}

const { primitiveLines, semanticLines } = buildMode('light');

let css = `/* AUTO-GENERATED by scripts/build-tokens.mjs from tokens/light/*.json - do not edit by hand. */\n\n:root {\n`;
css += `  /* Primitives */\n${primitiveLines.join('\n')}\n\n`;
css += `  /* Semantic tokens (light mode) */\n${semanticLines.join('\n')}\n`;
css += `}\n`;

if (modes.includes('dark')) {
  const dark = buildMode('dark');
  css += `\n.dark {\n  /* Semantic tokens (dark mode) */\n${dark.semanticLines.join('\n')}\n}\n`;
} else {
  css += `\n/* No dark mode tokens yet - add tokens/dark/{primitives,tokens}.json and re-run this script. */\n`;
}

mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, css);
console.log(`[build-tokens] Wrote ${path.relative(process.cwd(), outFile)}`);
